#!/bin/bash
~/.fehbg &
sxhkd -c $HOME/.config/berry/sxhkdrc &
$HOME/.config/polybar/launch.sh &

# Set decoration geometry
berryc border_width       2
berryc inner_border_width 0
berryc title_height       0
berryc edge_gap           0 32 0 0

# Set decoration colors
berryc focus_color         7A8A75
berryc unfocus_color       282828
berryc inner_focus_color   7A8A75
berryc inner_unfocus_color 282828
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "JetBrains Mono Nerd Font-12"
