#!/bin/sh

# Run Terminal Applications (!)

test -s "$HOME"/.dmenurc && . "$HOME"/.dmenurc

cmd="$(dmenu_path | dmenu "$@")"

case $cmd in
    *\!) "${TERMINAL:-kitty}" -e "${cmd%?}" & ;;
    *)   "${cmd}" & ;;
esac
