#!/bin/bash

# --- ALIASES ---
alias ls="exa -a --icons --group-directories-first"

# Confirm for common actions
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Resource monitoring
alias df="df -h"
alias free="free -m"
alias topmem="ps auxf | sort -nr -k 4 | head -5"
alias topcpu="ps auxf | sort -nr -k 3 | head -5"

# Grep color output
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# Programs

if command -v /usr/bin/git >/dev/null 2>&1; then
  alias g="git"
  alias gc="git clone"
  alias gp="git pull"
  alias gC="git commit"
  alias ga="git add"
  alias gb="git branch"
fi

alias v="$EDITOR"
alias doas="sudo"
alias compile="sudo make clean install"

if command -v /usr/bin/tmux >/dev/null 2>&1; then
  alias ktmux="tmux kill-server"
fi
