#!/bin/bash
# --- EXPORTS ---
export HISTSIZE=1000
export HISTFILE=$XDG_CONFIG_HOME/bash/bash_hist
export HISTCONTROL=ignoredups:erasedups


export XDG_RUNTIME_DIR=$HOME/.local/share/1000
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_STATE_HOME=$HOME/.local/share

if [[ -d "$HOME/.local/bin" ]];
  then PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d "$HOME/.emacs.d/bin" ]];
  then PATH="$HOME/.emacs.d/bin:$PATH" 
fi

export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=kitty

export MANPAGER="$EDITOR +Man!"
export MANWIDTH="999"
export INPUTRC=$XDG_CONFIG_HOME/inputrc
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority

# --- nnn ---
export NNN_OPTS="cEHrxQ"
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$" # install bsdtar
