#!/bin/bash
# --- EXPORTS ---
export HISTSIZE=1000
export HISTFILE=$XDG_CONFIG_HOME/bash/bash_hist
export HISTCONTROL=ignoredups:erasedups


export XDG_RUNTIME_DIR=$HOME/.local/share/1000
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_STATE_HOME=$HOME/.local/share

if [[ -d "$HOME/.local/bin" ]];
  then PATH="$HOME/.local/bin:$PATH"
fi

case $EDITOR in
  nvim)         export $EDITOR=nvim ;;
  vim)          export $EDITOR=vim ;;
  nano)         export $EDITOR=nano ;;
  *)            echo "Please set a EDITOR!" ;;
esac

case $BROWSER in
  firefox)      export $BROWSER=firefox ;;
  qutebrowser)  export $BROWSER=qutebrowser ;;
  chromium)     export $BROWSER=chromium ;;
  *)            echo "Please set a BROWSER!" ;;
esac

export TERM=st

export MANPAGER="$EDITOR +Man!"
export MANWIDTH="999"
export INPUTRC=$XDG_CONFIG_HOME/inputrc
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
