#!/bin/bash
# --- EXPORTS ---
export HISTSIZE=1000
export HISTFILE=$XDG_CONFIG_HOME/bash/bash_hist
export HISTCONTROL=ignoredups:erasedups


export XDG_RUNTIME_DIR=$HOME/.local/share/1000
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_STATE_HOME=$HOME/.local/share

if [[ -d "$HOME/.local/bin" ]];
  then PATH="$HOME/.local/bin:$PATH"
fi

export EDITOR=nvim
export VISUAL=nvim
export BROWSER=qutebrowser
export TERM=st

export MANPAGER="$EDITOR +Man!"
export MANWIDTH="999"
export INPUTRC=$XDG_CONFIG_HOME/inputrc
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
