#!/bin/sh

# autostart
killall picom
killall dunst

feh --bg-fill  "$(xdg-user-dir PICTURES)/Wallpapers/nightcity.png"
sxhkd &
xsetroot -cursor_name left_ptr
/usr/libexec/polkit-gnome-authentication-agent-1 &
dunst &
xrdb -merge $HOME/.Xresources &
urxvtd --quiet --opendisplay --fork
picom -b --experimental-backends --config $HOME/.config/picom.conf &

# bspwm
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focused_border_color	"#32C732"
#bspc config normal_border_color		"#3B3B3B"
